name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14'

      - name: clone
        uses: actions/checkout@v2.3.4

      - name: build
        run: |
          cd ${{github.workspace}}/mili
          npm install
          CI=false npm run build
          
      - name: transfer
        uses: garygrossgarten/github-action-ftp@release
        with:
          local: ${{github.workspace}}/mili/dist
          remote: ${{secrets.SERVER_DST_FOLDER}}/dist
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          rmRemote: true
          dotfiles: true

      - name: reload
        run: |
          sshpass -p ${{secrets.SERVER_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_IP}} "nginx -s reload"
